#!/bin/bash -l
#PBS -A gpu_hack
#PBS -N test_s3_mn_n2
#PBS -l walltime=00:20:00
#PBS -l select=2
#PBS -l place=scatter
#PBS -l filesystems=home:flare
#PBS -q gpu_hack
#PBS -j oe


projdir=${PBS_O_WORKDIR}  # Submit from the BioM3-dev directory
cd ${projdir}

module load frameworks
source ./venvs/biom3-env/bin/activate
source environment.sh

# 2 nodes x 12 tiles per node = 24 ranks
NUM_NODES=2
NGPU_PER_NODE=12

# Direct output to log file
mkdir -p logs
log_fpath=logs/test_stage3_multinode_n2_${PBS_JOBID}.o

./scripts/test_stage3_multinode.sh \
    ${NUM_NODES} \
    ${NGPU_PER_NODE} \
> ${log_fpath} 2>&1
