#!/bin/bash -l
#PBS -A NLDesignProtein
#PBS -N stage3_finetune_v1_ft16_n4_fluc
#PBS -l walltime=01:00:00
#PBS -l select=4
#PBS -l place=scatter
#PBS -l filesystems=home:flare
#PBS -q debug-scaling
#PBS -j oe
# PBS -M <emailaddress>
# PBS -m be


projdir=${PBS_O_WORKDIR}  # Should submit job from the BioM3-dev directory
cd ${projdir}

module load frameworks
source ./venvs/biom3-env/bin/activate

# Configurations to edit
config_path=./configs/stage3_training/finetune_v1.json  # JSON config file
num_nodes=4                     # Should match num requested nodes in PBS header
epochs=300                      # Number of epochs to finetune
use_wandb=False                 # set to False to disable wandb (requires WANDB_API_KEY exported when True)
resume_from_checkpoint="None"     # None to start finetuning fresh
pretrained_weights="/flare/NLDesignProtein/abigail/BioM3-projects/prompt_ablationapr2026/luciferase/outputs/Stage3_enriched/finetuning/checkpoints/fluc_enriched_finetune_v1_ft16_n1_d12_e300_V20260504_232324/single_model.best.pth"  # Path to pretrained weights (.bin)
finetune_last_n_blocks=1        # Number of last transformer blocks to unfreeze
finetune_last_n_layers=16       # Number of last layers per block to unfreeze
primary_data_path="/flare/NLDesignProtein/abigail/BioM3-projects/prompt_ablationapr2026/luciferase/outputs/embeddings/finetuning/fluc_enriched.compiled_emb.hdf5"
prefix=fluc_enriched            # Prefix prepended to run_id

# Constant configurations
num_devices=12                  # number of devices per node
device=xpu                      # device available (cuda, xpu)
batch_size=16
checkpoint_every_n_epochs=10

# Construct the run ID
datetime=$(date +%Y%m%d_%H%M%S)
config_name=$(basename "${config_path}" .json)
run_id=${prefix}_${config_name}_ft${finetune_last_n_layers}_n${num_nodes}_d${num_devices}_e${epochs}_V${datetime}

# Direct output to log file
mkdir -p logs
log_fpath=logs/${run_id}.${PBS_JOBID}.o

source environment.sh
./scripts/stage3_train_multinode.sh \
    ${config_path} \
    ${num_nodes} \
    ${num_devices} \
    ${device} \
    ${run_id} \
    --epochs ${epochs} \
    --resume_from_checkpoint ${resume_from_checkpoint} \
    --finetune True \
    --pretrained_weights ${pretrained_weights} \
    --finetune_last_n_blocks ${finetune_last_n_blocks} \
    --finetune_last_n_layers ${finetune_last_n_layers} \
    --primary_data_path ${primary_data_path} \
    --batch_size ${batch_size} \
    --checkpoint_every_n_epochs ${checkpoint_every_n_epochs} \
    --wandb ${use_wandb} \
> ${log_fpath} 2>&1
