#!/bin/bash -l
#PBS -A NLDesignProtein
#PBS -N job_test_hydra_2node_4gpu
#PBS -l walltime=00:20:00
#PBS -l select=2
#PBS -l filesystems=home:grand
#PBS -q debug
#PBS -M addi.howe+pbs-polaris@gmail.com
#PBS -m be

projdir=${PBS_O_WORKDIR}  # Should submit job from the BioM3-dev directory

cd ${projdir}  # TODO: verify that directory ends in BioM3-dev

module use /soft/modulefiles
module load conda
conda activate base
source ./venvs/biom3-env/bin/activate

NRANKS=$(wc -l < "${PBS_NODEFILE}")
NGPU_PER_RANK=$(nvidia-smi -L | wc -l)
NGPUS="$((${NRANKS}*${NGPU_PER_RANK}))"
echo "NRANKS: ${NRANKS}, NGPU_PER_RANK: ${NGPU_PER_RANK}, NGPUS: ${NGPUS}"

NNODES=2
NGPUS=4

datetime=$(date +%Y%m%d_%H%M%S)

wandb_api_key="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"
configdir=./configs
config_name=config_${NNODES}node_${NGPUS}gpu

version_name="V${datetime}_${NNODES}node_${NGPUS}gpu"
epoch=2 # number of epochs
resume_from_checkpoint='null'

./scripts/hydra_PL_train_transformer.sh \
    $wandb_api_key $configdir $config_name \
    $version_name \
    $epoch \
    $resume_from_checkpoint
