#!/bin/bash -l
#PBS -A NLDesignProtein
#PBS -N ft_run1_base_sh3
#PBS -l walltime=01:00:00
#PBS -l select=2
#PBS -l place=scatter
#PBS -l filesystems=home:flare
#PBS -q debug
#PBS -j oe
# PBS -M addi.howe@gmail.com
# PBS -m be


projdir=${PBS_O_WORKDIR}  # Should submit job from the BioM3-dev directory
cd ${projdir}

module load frameworks
source ./venvs/biom3-env/bin/activate

# Configurations to edit
config_path=./configs/stage3_training/finetune_v1.json
num_nodes=2           # Should match num requested nodes in PBS header
epochs=50                        # Number of epochs to finetune
use_wandb=True                  # set to False to disable wandb (requires WANDB_API_KEY exported when True)
resume_from_checkpoint=None     # None to start finetuning fresh
pretrained_weights=./weights/ProteoScribe/run1_base_proteoscribe.ckpt
finetune_last_n_blocks=1        # Number of last transformer blocks to unfreeze
finetune_last_n_layers=-1        # Number of last layers per block to unfreeze
primary_data_path=./outputs/run1_base/SH3_embeddings/SH3_run1_base.compiled_emb.hdf5
split_manifest=outputs/run1_base/SH3_embeddings/SH3_run1_base.split_manifest.json

# Constant configurations
num_devices=12                  # number of devices per node
device=xpu                      # device available (cuda, xpu)

# Construct the run ID
datetime=$(date +%Y%m%d_%H%M%S)
config_name=$(basename "${config_path}" .json)
run_id=${config_name}_ft${finetune_last_n_blocks}-${finetune_last_n_layers}_n${num_nodes}_d${num_devices}_e${epochs}_V${datetime}

# Direct output to log file
mkdir -p logs
log_fpath=logs/${run_id}.${PBS_JOBID}.o

source environment.sh
./scripts/stage3_train_multinode.sh \
    ${config_path} \
    ${num_nodes} \
    ${num_devices} \
    ${device} \
    ${run_id} \
    --epochs ${epochs} \
    --resume_from_checkpoint ${resume_from_checkpoint} \
    --finetune True \
    --pretrained_weights ${pretrained_weights} \
    --finetune_last_n_blocks ${finetune_last_n_blocks} \
    --finetune_last_n_layers ${finetune_last_n_layers} \
    --primary_data_path ${primary_data_path} \
    --wandb ${use_wandb} \
    --split_manifest_path "${split_manifest}" \
> ${log_fpath} 2>&1
